name: Open Merge Release PR

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'What release branch do you want to use to open the PR (eg: release/1.0.0) '
        default: 'release/'
        required: true

jobs:
  openMergeReleasePR:
    runs-on: ubuntu-latest
    name: Open Merge Release PR
    env:
      MERGE_BRANCH: merge-${{github.event.inputs.releaseBranch}}-to-develop
      DEVELOP_BRANCH: develop

    steps:
    - name: Checkout ${{github.event.inputs.releaseBranch}}
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{github.event.inputs.releaseBranch}}

    - name: Create Merge Branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        branch: ${{env.MERGE_BRANCH}}
        
    - name: Rebase with develop
      uses: peter-evans/rebase@v1
      with:
        base: ${{env.DEVELOP_BRANCH}}
        
    - name: Open PR
      uses: TreTuna/sync-branches@1.2.0
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        FROM_BRANCH: ${{env.MERGE_BRANCH}}
        TO_BRANCH: ${{env.DEVELOP_BRANCH}}
        PULL_REQUEST_TITLE: Merge ${{github.event.inputs.releaseBranch}} to ${{env.DEVELOP_BRANCH}}
