# This is a basic workflow that is manually triggered

name: Open Sync Release PR

on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        description: 'What release branch do you want to use to open the PR (eg: release/1.0.0) '
        default: 'release/'
        required: true

jobs:
  openSyncReleasePR:
    runs-on: ubuntu-latest

    steps:
    - name: Echo releaseBranch
      run: echo "Opening PR to merge to develop from ${{ github.event.inputs.releaseBranch }}"
