name: Automated Sync PR

on:
  push:
    branches: [ release/** ]
  workflow_dispatch:

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
#       - name: branch
#         run: |
#           content=`echo date`
#           echo "::set-output name=date::$content"
#       - run: |
#           echo "${{steps.branch.outputs.date}}"
#       - name: Delete MERGE_BRANCH
#         uses: dawidd6/action-delete-branch@v3
#         with:
#           github_token: ${{github.token}}
#           branches: ${{env.MERGE_BRANCH}}
#       - name: Read package.json
#         id: package
#         uses: juliangruber/read-file-action@v1
#         with:
#           path: ./package.json
#       - name: Echo package.json
#         run: echo ${{ steps.package.outputs.content }}
      - name: Checkout
        uses: actions/checkout@v2
      - id: set_var
        run: |
          content=`cat ./src/package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
#       - name: Create MERGE_BRANCH
#         uses: peterjgrainger/action-create-branch@v2.0.1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           branch: ${{env.MERGE_BRANCH}}
#       - name: Checkout MERGE_BRANCH
#         uses: actions/checkout@v2
#         with:
#           ref: ${{env.MERGE_BRANCH}}
#       - name: Rebase with ${{env.DEVELOP_BRANCH}}
#         uses: peter-evans/rebase@v1
#         with:
#           base: ${{env.DEVELOP_BRANCH}}
#       - name: Open Pull Request
#         id: pull
#         uses: tretuna/sync-branches@1.2.0
#         with:
#           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#           FROM_BRANCH: ${{env.MERGE_BRANCH}}
#           TO_BRANCH: ${{env.DEVELOP_BRANCH}}
          
